with-expecter: false
packages:
  election-agent/internal/zone:
    config:
      dir: internal/zone
      inpackage: true
    interfaces:
      ZoneManager:
  election-agent/internal/driver:
    config:
      dir: internal/driver
      inpackage: true
    interfaces:
      RedisConn:
      RedisPool:
