with-expecter: false
packages:
  election-agent/internal/zone:
    config:
      dir: internal/zone
      inpackage: true
    interfaces:
      ZoneManager:
  github.com/go-redsync/redsync/v4/redis:
    interfaces:
      Script:
      Pool:
      Conn:
