with-expecter: false
packages:
  election-agent/internal/zone:
    config:
      dir: internal/zone
      inpackage: true
    interfaces:
      ZoneManager:
  election-agent/internal/driver/redlock:
    config:
      dir: internal/driver/redlock
      inpackage: true
    interfaces:
      Conn:
