apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: election-agent
    app.kubernetes.io/name: election-agent
    app.kubernetes.io/instance: election-agent-kz1
    app.kubernetes.io/version: 1.0.0
  name: election-agent
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: election-agent-kz1
      app.kubernetes.io/name: election-agent
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        sidecar.istio.io/proxyCPU: 500m
        sidecar.istio.io/proxyCPULimit: 1000m
        sidecar.istio.io/proxyMemory: 100Mi
        sidecar.istio.io/proxyMemoryLimit: 200Mi
      labels:
        app: election-agent
        app.kubernetes.io/instance: election-agent-kz1
        app.kubernetes.io/name: election-agent
        app.kubernetes.io/version: 1.0.0
    spec:
      restartPolicy: Always
      serviceAccountName: election-agent
      automountServiceAccountToken: true
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: election-agent-kz1
              app.kubernetes.io/name: election-agent
      containers:
        - name: election-agent
          envFrom:
          - configMapRef:
              name: env-vars
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: grpc
              protocol: TCP
          image: election-agent:distroless-base-nossl
          imagePullPolicy: Never
          livenessProbe:
            grpc:
              port: 443
              service: liveness
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            grpc:
              port: 443
              service: readiness
            failureThreshold: 2
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          resources:
            requests:
              cpu: 1000m
              memory: 400Mi
            limits:
              cpu: 1500m
              memory: 1000Mi
