apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - deployment_util.yaml
  - service.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml

configMapGenerator:
- name: env-vars
  env: env-vars.env
