apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: election-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: election-agent
subjects:
- kind: ServiceAccount
  name: election-agent
