apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: election-agent
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - "apps"
  resources:
  - services
  - deployments
  - replicasets
  verbs:
  - get
