FROM golang:1.22 as build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 make build


FROM gcr.io/distroless/base-nossl-debian12

COPY --from=build /src/election-agent /app/

CMD ["/app/election-agent"]
EXPOSE 80 443
