apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: election-agent-util
    app.kubernetes.io/instance: election-agent-util
    app.kubernetes.io/version: e2e-test
  name: election-agent-util
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: election-agent-util
      app.kubernetes.io/name: election-agent-util
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: election-agent-util
        app.kubernetes.io/name: election-agent-util
        app.kubernetes.io/version: e2e-test
    spec:
      restartPolicy: Always
      serviceAccountName: election-agent
      automountServiceAccountToken: true
      containers:
        - name: election-agent-util
          image: election-agent-util:e2e-test
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 500m
              memory: 1000Mi
            limits:
              cpu: 4000m
              memory: 4000Mi
