# redis-a StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-a
spec:
  serviceName: redis-g1
  selector:
    matchLabels:
      instance: redis-a
      name: redis
  replicas: 2
  template:
    metadata:
      labels:
        instance: redis-a
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        ports:
        - containerPort: 6379
---
# redis-b StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-b
spec:
  serviceName: redis-g2
  selector:
    matchLabels:
      instance: redis-b
      name: redis
  replicas: 2
  template:
    metadata:
      labels:
        instance: redis-b
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        ports:
        - containerPort: 6379
---
# redis-c StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-c
spec:
  serviceName: redis-g3
  selector:
    matchLabels:
      instance: redis-c
      name: redis
  replicas: 2
  template:
    metadata:
      labels:
        instance: redis-c
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:7.2
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
          exec:
            command:
            - sh
            - -c
            - redis-cli ping
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
          limits:
            cpu: 1000m
            memory: 500Mi
        ports:
        - containerPort: 6379
---
# redis-a headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-g1
  labels:
    service: redis-g1
    name: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    instance: redis-a
    name: redis
---
# redis-b headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-g2
  labels:
    service: redis-g2
    name: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    instance: redis-b
    name: redis
---
# redis-c headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-g3
  labels:
    service: redis-g3
    name: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    instance: redis-c
    name: redis
