apiVersion: v1
kind: ConfigMap
metadata:
  name: zone-coordinator-config
data:
  ZC_ENV: production
  ZC_PORT: "80"
  ZC_ZONE: z1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: zone-coordinator
    app.kubernetes.io/instance: zone-coordinator
    app.kubernetes.io/version: e2e-test
  name: zone-coordinator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: zone-coordinator
      app.kubernetes.io/name: zone-coordinator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: zone-coordinator
        app.kubernetes.io/name: zone-coordinator
        app.kubernetes.io/version: e2e-test
    spec:
      restartPolicy: Always
      serviceAccountName: default
      containers:
        - name: zone-coordinator
          envFrom:
            - configMapRef:
                name: zone-coordinator-config
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          image: zone-coordinator:e2e-test
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              port: 80
              path: /livez
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 80
              path: /readyz
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: zone-coordinator
spec:
  type: ClusterIP
  ports:
    - name: http
      targetPort: http
      port: 80
  selector:
    app.kubernetes.io/instance: zone-coordinator
    app.kubernetes.io/name: zone-coordinator
